#! /bin/bash

exercices_ok=0
nb_exercices=3

parsetemplate -o student/gcd.py gcd.tpl.py
output=$(run_student python student/gcd.py 2>&1)
expected_output=$(printf "OK")
if [[ "$output" == "$expected_output" ]]; then
	feedback --feedback "Your answer is correct" --id gcd
    exercices_ok=$(($exercices_ok + 1))
else
	output=$(echo "$output" | sed -e 's/^/\t/' | sed 's/%/%%/g')
    output=$(printf "Wrong answer:\n\n::\n\n$output\n")
	feedback --feedback "$output" --id gcd
fi

parsetemplate -o student/multi.py multi.tpl.py
output=$(run_student python student/multi.py 2>&1)
expected_output=$(printf "OK")
if [[ "$output" == "$expected_output" ]]; then
	feedback --feedback "Your answer is correct" --id multi
    exercices_ok=$(($exercices_ok + 1))
else
	output=$(echo "$output" | sed -e 's/^/\t/' | sed 's/%/%%/g')
	output=$(printf "Wrong answer:\n\n::\n\n$output\n")
	feedback --feedback "$output" --id multi
fi

parsetemplate -o student/multi_multi.py multi_multi.py
output=$(run_student python student/multi_multi.py 2>&1)
expected_output=$(printf "OK")
if [[ "$output" == "$expected_output" ]]; then
	feedback --feedback "Your answer is correct" --id multi_multi
    exercices_ok=$(($exercices_ok + 1))
else
	output=$(echo "$output" | sed -e 's/^/\t/' | sed 's/%/%%/g')
	output=$(printf "Wrong answer:\n\n::\n\n$output\n")
	feedback --feedback "$output" --id multi_multi
fi

amount_done=$(($exercices_ok*100/$nb_exercices))
if [[ $exercices_ok -eq $nb_exercices ]]; then
	feedback --result success --feedback "You solved all the exercices" --grade  $amount_done
else
	feedback --result failed --feedback "You made an error, see below" --grade     $amount_done
fi